version: 2
updates:
  - package-ecosystem: "npm" # or any other package manager like "maven", "ruby", etc.
    directory: "/" # location of your package file
    schedule:
      interval: "weekly" # Can be "daily", "weekly", or "monthly"
