FROM openjdk:23-oracle

ENV JAVA_OPTS " -Xms512m -Xmx512m -Djava.security.egd=file:/dev/./urandom"

WORKDIR application

COPY ../../../target/hearu-backend-service-0.0.1-SNAPSHOT.jar ./

ENTRYPOINT ["java", "-jar", "hearu-backend-service-0.0.1-SNAPSHOT.jar"]