name: Dependabot Update

on:
  push:
    branches:
      - main # or whatever branch you want to trigger the workflow on
  workflow_dispatch: # This allows manual triggering of the workflow
  
jobs:
  dependabot-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Dependabot
        uses: dependabot/fetch-metadata@v1

      - name: Run Dependabot
        run: |
          git config --global user.name "dependabot"
          git config --global user.email "dependabot@github.com"
          dependabot update
