name: Manual Dependabot Trigger

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  trigger-dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to update dependencies
      pull-requests: write  # Required to create PRs

    steps:
      - name: Run Dependabot
        uses: github/dependabot-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_PAT }}

