name: Manual Dependabot Update

on:
  workflow_dispatch:
    inputs:
      package_ecosystem:
        description: 'Type of dependencies to update'
        required: true
        default: 'npm'
        type: choice
        options:
          - npm
          - maven
          - pip
          - bundler
          - cargo
          - composer
          - nuget
          - gradle
          - gomod
          - docker
      directory:
        description: 'Directory with dependency files'
        required: true
        default: '/'
        type: string
      dependency_name:
        description: 'Specific dependency to update (optional)'
        required: false
        type: string

jobs:
  trigger-dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Trigger Dependabot update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "${{ inputs.dependency_name }}" ]; then
            echo "Triggering Dependabot for all ${{ inputs.package_ecosystem }} dependencies in ${{ inputs.directory }}"
            gh api \
              --method POST \
              repos/${{ github.repository }}/dependabot/updates \
              -f package-ecosystem="${{ inputs.package_ecosystem }}" \
              -f directory="${{ inputs.directory }}" \
              -f vendor=false
          else
            echo "Triggering Dependabot for ${{ inputs.dependency_name }} in ${{ inputs.package_ecosystem }}"
            gh api \
              --method POST \
              repos/${{ github.repository }}/dependabot/updates \
              -f package-ecosystem="${{ inputs.package_ecosystem }}" \
              -f directory="${{ inputs.directory }}" \
              -f dependency-name="${{ inputs.dependency_name }}" \
              -f vendor=false
          fi
