name: Run Renovate

on:
  workflow_dispatch:  # This triggers the workflow manually (you'll trigger it from GitHub UI)

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Renovate
        uses: renovatebot/github-action@v41.0.16
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}  # Uses the token you stored in GitHub Secrets
          
      - name: Run Renovate
        run: |
          renovate --config-file ./renovate.json  # Optional if you have custom configuration


